In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from datetime import datetime

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/data-crunch-round-1/sample_submission.csv
/kaggle/input/data-crunch-round-1/train.csv
/kaggle/input/data-crunch-round-1/test.csv

In [3]:
df = pd.read_csv("/kaggle/input/data-crunch-round-1/train.csv")

def to_date(year, month, day):
    return datetime(year=2018+year, month=month, day=day)

def from_date(date):
    return date.year-2018, date.month, date.day

df['Date'] = df.apply(lambda row: datetime(year=2018+row['Year'], 
                                                     month=row['Month'], 
                                                     day=row['Day']), axis=1)
df['Date'] = df.apply(lambda row: to_date(row['Year'], row['Month'], row['Day']), axis=1)
df.set_index('Date', inplace=True)
target = ['Avg_Temperature', 'Radiation', 'Rain_Amount','Wind_Speed', 'Wind_Direction']
df = df[['kingdom'] + target]
kingdoms = [df[df['kingdom']==k] for k in df['kingdom'].unique()]


def predict(data, n, th=100):
    N = len(data)
    fft_values = np.fft.fft(data)
    freqs = np.fft.fftfreq(N, d=1)
    extended_indexes = np.arange(N+1, N+1+n)

    reconstructed_fet = np.zeros(len(extended_indexes), dtype=np.complex128)
    
    threshold = th
    for i, freq in enumerate(freqs[:N//2]): 
        if abs(freq) > threshold:
            continue
        amplitude = np.abs(fft_values[i]) / N
        phase = np.angle(fft_values[i])
        reconstructed_fet += amplitude * np.exp(1j * (2 * np.pi * freq * extended_indexes + phase))

    reconstructed_fet = np.real(reconstructed_fet)
    return reconstructed_fet


def predict_many(data, n, th=0.4):
    return np.array([predict(fet, n, th) for fet in data])

def create_dataframe(indexes, data, columns, default=dict()):
    df = pd.DataFrame(data, index=indexes, columns=columns)
    for key, val in default.items():
        df.insert(0, key, val)
    return df

def create_next_date_window_n(start, n):
    dates = np.full(n, start, dtype='datetime64[ns]')
    indexes = np.arange(1, n+1)
    timedeltas = np.array(indexes, dtype='timedelta64[D]')
    return dates + timedeltas

def create_next_date_window_stop(start, end):
    n = (end-start).days
    return create_next_date_window_n(start, n)

In [13]:
def analyze_periods(data):
    N = len(data)
    fft_values = np.fft.fft(data)
    freqs = np.fft.fftfreq(N, d=1)
    
    magnitudes = np.abs(fft_values[:N//2]) / N
    sorted_indices = np.argsort(magnitudes)[::-1]
    
    periods = [1 / freqs[i] if freqs[i] != 0 else np.inf for i in sorted_indices]
    
    return periods

In [15]:
df[df['kingdom']=='Arcadia'][target].to_numpy().T[0]

array([25.5, 25.8, 26. , ..., 25. , 24. , 23.8])

In [17]:
df[df['kingdom']=='Arcadia'][target].to_numpy().T[0][-10:]

array([24.2, 24.3, 24.6, 23.1, 23.9, 24.8, 25.2, 25. , 24. , 23.8])

In [18]:
analyze_periods(df[df['kingdom']=='Arcadia'][target].to_numpy().T[0])

[inf,
 354.0,
 177.0,
 404.5714285714286,
 1416.0,
 188.8,
 236.0,
 566.4,
 708.0,
 283.2,
 472.0,
 118.0,
 123.1304347826087,
 2832.0,
 944.0,
 101.14285714285715,
 166.58823529411765,
 33.31764705882353,
 57.795918367346935,
 62.93333333333334,
 217.84615384615384,
 91.35483870967742,
 257.4545454545455,
 70.8,
 37.760000000000005,
 69.07317073170732,
 202.2857142857143,
 53.43396226415094,
 314.66666666666663,
 48.0,
 134.85714285714286,
 51.490909090909085,
 19.943661971830984,
 17.26829268292683,
 141.6,
 49.684210526315795,
 28.039603960396043,
 157.33333333333331,
 48.827586206896555,
 15.063829787234043,
 19.006711409395972,
 13.615384615384615,
 38.79452054794521,
 38.270270270270274,
 42.90909090909091,
 88.5,
 12.990825688073395,
 64.36363636363637,
 17.163636363636364,
 17.06024096385542,
 37.26315789473684,
 113.28,
 35.848101265822784,
 20.085106382978722,
 11.465587044534415,
 12.756756756756756,
 19.804195804195803,
 149.05263157894737,
 17.48148148148148,
 61.56521739130435,
 26.97142857142857,
 15.308108108108108,
 20.228571428571428,
 104.88888888888889,
 19.397260273972606,
 60.255319148936174,
 16.275862068965516,
 22.838709677419356,
 31.12087912087912,
 18.63157894736842,
 18.75496688741722,
 10.646616541353383,
 35.4,
 10.150537634408602,
 94.4,
 44.25,
 36.30769230769231,
 20.37410071942446,
 17.924050632911392,
 59.0,
 9.224755700325733,
 20.823529411764707,
 17.81132075471698,
 16.36994219653179,
 50.57142857142858,
 31.46666666666667,
 41.04347826086956,
 10.809160305343513,
 21.618320610687025,
 34.96296296296296,
 13.421800947867299,
 47.2,
 24.0,
 12.206896551724139,
 9.16504854368932,
 4.977152899824253,
 9.698630136986303,
 8.962025316455696,
 13.358490566037736,
 18.880000000000003,
 6.775119617224881,
 85.81818181818181,
 12.31304347826087,
 76.54054054054055,
 65.86046511627907,
 8.99047619047619,
 13.950738916256158,
 12.931506849315069,
 4.488114104595879,
 4.3369065849923425,
 30.127659574468087,
 7.169620253164557,
 6.064239828693791,
 8.713846153846154,
 41.64705882352941,
 19.666666666666664,
 80.91428571428571,
 15.14438502673797,
 13.050691244239632,
 14.597938144329898,
 9.346534653465346,
 10.606741573033709,
 23.6,
 15.646408839779005,
 10.042553191489361,
 6.293333333333334,
 5.9,
 9.86759581881533,
 13.485714285714286,
 11.105882352941176,
 22.125,
 6.210526315789474,
 56.64,
 24.62608695652174,
 4.657894736842105,
 7.492063492063492,
 7.115577889447237,
 4.6048780487804875,
 13.11111111111111,
 20.67153284671533,
 9.63265306122449,
 16.658823529411766,
 11.149606299212598,
 19.135135135135137,
 52.44444444444444,
 8.453731343283582,
 30.782608695652176,
 4.523961661341853,
 9.047923322683706,
 7.910614525139666,
 6.857142857142857,
 4.7596638655462185,
 6.555555555555555,
 72.61538461538461,
 28.32,
 21.784615384615385,
 9.936842105263159,
 8.933753943217665,
 9.076923076923077,
 11.8,
 14.16,
 7.4136125654450264,
 27.764705882352942,
 8.634146341463415,
 7.695652173913044,
 20.52173913043478,
 13.882352941176471,
 67.42857142857143,
 14.827225130890053,
 32.93023255813954,
 4.350230414746544,
 11.512195121951219,
 5.664,
 4.411214953271028,
 11.60655737704918,
 13.233644859813085,
 10.335766423357665,
 6.679245283018868,
 42.26865671641791,
 9.971830985915492,
 5.721212121212121,
 16.0,
 9.135483870967741,
 34.53658536585366,
 15.56043956043956,
 5.7560975609756095,
 12.421052631578949,
 4.098408104196816,
 7.452631578947368,
 11.899159663865547,
 97.65517241379311,
 6.890510948905109,
 10.007067137809187,
 3.2777777777777777,
 31.820224719101123,
 5.205882352941177,
 3.6971279373368144,
 5.0212765957446805,
 3.055016181229773,
 13.814634146341461,
 32.18181818181819,
 6.510344827586207,
 10.488888888888889,
 23.024390243902438,
 39.88732394366197,
 4.832764505119454,
 3.129281767955801,
 6.116630669546437,
 12.872727272727271,
 8.161383285302593,
 7.592493297587131,
 13.295774647887326,
 3.9333333333333336,
 12.530973451327434,
 5.937106918238994,
 10.18705035971223,
 11.328,
 11.0625,
 15.391304347826088,
 5.6414342629482075,
 5.779591836734694,
 21.134328358208954,
 5.744421906693712,
 128.72727272727275,
 24.842105263157897,
 12.051063829787234,
 10.373626373626374,
 11.654320987654321,
 11.949367088607595,
 27.495145631067963,
 8.74074074074074,
 5.630218687872763,
 8.76780185758514,
 3.776,
 8.09142857142857,
 11.702479338842975,
 3.185601799775028,
 6.025531914893617,
 14.75,
 14.08955223880597,
 4.8743545611015495,
 18.270967741935483,
 4.290909090909091,
 18.38961038961039,
 5.924686192468619,
 3.8218623481781373,
 3.858310626702997,
 7.280205655526992,
 3.7559681697612737,
 3.716535433070866,
 5.652694610778443,
 7.08,
 10.114285714285714,
 16.46511627906977,
 6.742857142857143,
 10.298181818181819,
 7.224489795918367,
 83.29411764705883,
 4.865979381443299,
 18.153846153846153,
 4.68099173553719,
 11.193675889328063,
 4.891191709844559,
 4.942408376963351,
 10.07829181494662,
 5.37381404174573,
 3.6683937823834194,
 4.317073170731708,
 5.863354037267081,
 5.875518672199171,
 5.912317327766179,
 8.378698224852071,
 8.068376068376068,
 2.245836637589215,
 2.3798319327731092,
 14.905263157894735,
 14.673575129533678,
 6.265486725663717,
 9.408637873754152,
 12.15450643776824,
 4.816326530612245,
 15.733333333333334,
 3.6779220779220783,
 9.31578947368421,
 6.586046511627907,
 6.873786407766991,
 3.03862660944206,
 3.781041388518024,
 4.538461538461538,
 3.312280701754386,
 3.1784511784511786,
 3.0849673202614376,
 5.987315010570824,
 25.061946902654867,
 5.732793522267207,
 4.189349112426036,
 3.081610446137106,
 5.25417439703154,
 18.509803921568626,
 6.465753424657534,
 2.198757763975155,
 4.908145580589255,
 14.231155778894474,
 6.103448275862069,
 9.194805194805195,
 22.476190476190478,
 8.232558139534884,
 2.158536585365854,
 7.394255874673629,
 6.129870129870129,
 9.79930795847751,
 4.589951377633711,
 9.471571906354514,
 2.451948051948052,
 21.454545454545453,
 5.585798816568047,
 4.438871473354232,
 7.133501259445843,
 21.953488372093023,
 3.6731517509727625,
 5.404580152671756,
 4.9597197898423815,
 7.7377049180327875,
 2.9841938883034773,
 4.545746388443018,
 5.343396226415094,
 3.2365714285714287,
 6.726840855106888,
 5.2835820895522385,
 3.4578754578754576,
 3.911602209944751,
 16.18285714285714,
 3.4621026894865525,
 2.0823529411764707,
 7.823204419889502,
 4.051502145922747,
 13.681159420289855,
 6.07725321888412,
 5.1678832116788325,
 4.6350245499181675,
 2.7415295256534367,
 6.012738853503184,
 21.293233082706767,
 4.277945619335347,
 2.391891891891892,
 18.038216560509554,
 2.272873194221509,
 6.5707656612529,
 5.974683544303797,
 10.934362934362936,
 4.201780415430267,
 3.8847736625514404,
 17.7,
 10.567164179104477,
 8.403560830860535,
 7.674796747967481,
 5.80327868852459,
 8.581818181818182,
 5.6079207920792085,
 3.2108843537414966,
 7.336787564766839,
 3.363420427553444,
 5.003533568904594,
 5.827160493827161,
 4.39751552795031,
 3.3835125448028673,
 16.757396449704142,
 24.413793103448278,
 6.975369458128079,
 3.2891986062717766,
 4.363636363636364,
 2.5698729582577133,
 3.7962466487935655,
 2.6393289841565704,
 8.208695652173914,
 5.574803149606299,
 4.3039513677811545,
 2.3758389261744965,
 7.716621253405994,
 4.495238095238095,
 5.949579831932773,
 4.1647058823529415,
 3.3045507584597433,
 4.994708994708994,
 3.3239436619718314,
 3.626120358514725,
 5.196330275229358,
 2.6319702602230484,
 5.030195381882771,
 3.4244256348246678,
 5.675350701402806,
 5.057142857142857,
 2.338563170933113,
 7.572192513368985,
 3.218181818181818,
 8.53012048192771,
 4.849315068493151,
 7.187817258883248,
 3.4327272727272726,
 3.3554502369668247,
 16.56140350877193,
 4.017021276595744,
 3.3956834532374103,
 9.833333333333332,
 5.093525179856115,
 7.009900990099011,
 2.4755244755244754,
 2.8067393458870167,
 3.8322056833558866,
 12.586666666666668,
 10.527881040892193,
 2.1325301204819276,
 5.552941176470588,
 6.758949880668258,
 28.60606060606061,
 3.9775280898876404,
 12.366812227074236,
 7.151515151515152,
 2.801186943620178,
 3.589353612167301,
 25.745454545454542,
 5.815195071868583,
 5.767820773930754,
 3.616858237547893,
 6.224175824175824,
 7.758904109589041,
 3.3475177304964543,
 3.9442896935933147,
 9.440000000000001,
 6.992592592592592,
 6.143167028199566,
 2.661654135338346,
 5.186813186813187,
 3.048439181916039,
 2.9779179810725553,
 8.114613180515759,
 4.951048951048951,
 29.81052631578947,
 5.53125,
 4.220566318926974,
 3.6494845360824746,
 5.851239669421488,
 6.525345622119816,
 32.55172413793103,
 10.850574712643677,
 22.299212598425196,
 3.7068062827225132,
 2.508414526129318,
 30.451612903225804,
 3.906206896551724,
 3.827027027027027,
 5.499029126213593,
 8.90566037735849,
 2.4288164665523158,
 3.4536585365853654,
 5.2250922509225095,
 3.098468271334792,
 4.808149405772496,
 3.621483375959079,
 7.375,
 2.085419734904271,
 2.0551523947750363,
 3.335689045936396,
 6.540415704387991,
 3.1431742508324083,
 3.5223880597014925,
 8.256559766763848,
 3.112087912087912,
 8.022662889518413,
 2.499558693733451,
 2.165137614678899,
 2.880976602238047,
 3.2,
 4.404354587869363,
 3.8013422818791947,
 7.932773109243698,
 2.925619834710744,
 5.542074363992172,
 7.298969072164949,
 2.2494042891183477,
 15.821229050279332,
 3.343565525383707,
 2.1405895691609977,
 4.158590308370044,
 3.8064516129032255,
 6.038379530916845,
 5.41491395793499,
 4.356923076923077,
 2.473362445414847,
 4.116279069767442,
 2.968553459119497,
 2.512866015971606,
 3.746031746031746,
 3.6923076923076925,
 11.373493975903614,
 2.258373205741627,
 6.840579710144928,
 3.2930232558139534,
 4.343558282208589,
 2.5910338517840805,
 4.022727272727273,
 6.0,
 14.523076923076923,
 12.642857142857144,
 8.479041916167665,
 3.57124842370744,
 8.184971098265896,
 5.2154696132596685,
 6.279379157427938,
 23.40495867768595,
 4.481012658227848,
 4.502384737678855,
 3.0418904403866813,
 6.9411764705882355,
 5.273743016759776,
 4.673267326732673,
 9.665529010238908,
 3.8373983739837403,
 2.883910386965377,
 11.559183673469388,
 8.353982300884956,
 2.1357466063348416,
 2.773751224289912,
 2.107142857142857,
 2.363939899833055,
 25.98165137614679,
 4.452830188679245,
 4.045714285714285,
 2.699714013346044,
 6.183406113537118,
 14.303030303030305,
 11.282868525896415,
 6.480549199084669,
 2.834834834834835,
 4.226865671641791,
 4.743718592964824,
 3.9831223628691985,
 7.2615384615384615,
 3.3875598086124405,
 16.95808383233533,
 10.26086956521739,
 28.897959183673468,
 6.169934640522875,
 13.747572815533982,
 5.263940520446097,
 2.099332839140104,
 5.2444444444444445,
 3.765957446808511,
 8.555891238670695,
 2.8123138033763655,
 6.710900473933649,
 4.575121163166398,
 44.952380952380956,
 3.5577889447236184,
 14.448979591836734,
 3.5802781289506953,
 5.467181467181468,
 3.863574351978172,
 7.552,
 2.8957055214723924,
 2.1885625965996907,
 3.407942238267148,
 2.356073211314476,
 4.72787979966611,
 2.2021772939346813,
 6.3355704697986575,
 3.9943582510578275,
 3.1820224719101127,
 2.3232157506152586,
 7.977464788732395,
 9.106109324758842,
 4.29742033383915,
 4.553054662379421,
 2.148710166919575,
 3.0256410256410255,
 3.351479289940828,
 2.993657505285412,
 8.0,
 20.977777777777778,
 4.968421052631579,
 2.215962441314554,
 2.3366336633663365,
 4.074820143884892,
 2.304312449145647,
 2.692015209125475,
 5.293457943925234,
 6.695035460992909,
 4.252252252252252,
 5.084380610412926,
 2.9873417721518987,
 15.475409836065575,
 4.597402597402597,
 5.0661896243291595,
 2.3024390243902437,
 2.671698113207547,
 2.636871508379888,
 8.607902735562309,
 3.1223814773980156,
 4.933797909407665,
 15.225806451612902,
 2.0931263858093128,
 2.62708719851577,
 10.223826714801445,
 4.627450980392156,
 4.767676767676768,
 45.67741935483871,
 10.411764705882353,
 5.075268817204301,
 2.5218165627782723,
 8.329411764705883,
 3.5136476426799006,
 7.433070866141732,
 5.03914590747331,
 4.5312,
 2.9623430962343096,
 2.3175122749590837,
 3.4833948339483394,
 8.045454545454547,
 16.857142857142858,
 4.310502283105023,
 3.1086717892425906,
 3.847826086956522,
 11.419354838709678,
 2.6295264623955434,
 3.2514351320321473,
 2.614958448753463,
 11.238095238095239,
 2.3482587064676617,
 29.5,
 6.321428571428572,
 3.6636481241914622,
 3.420289855072464,
 2.959247648902821,
 7.955056179775281,
 3.8115746971736204,
 2.600550964187328,
 2.0199714693295294,
 39.33333333333333,
 3.874145006839945,
 2.4863915715539946,
 2.733590733590734,
 5.509727626459144,
 2.8634984833164814,
 3.035369774919614,
 4.128279883381924,
 12.259740259740258,
 2.2674139311449157,
 3.5848101265822785,
 2.837675350701403,
 2.517333333333333,
 2.1213483146067413,
 5.313320825515947,
 5.102702702702703,
 2.3541147132169575,
 3.061621621621622,
 2.5863013698630137,
 16.090909090909093,
 3.367419738406659,
 4.034188034188034,
 6.237885462555066,
 3.955307262569833,
 2.3005686433793664,
 4.642622950819672,
 2.549054905490549,
 5.446153846153846,
 2.0028288543140027,
 23.21311475409836,
 3.7860962566844925,
 2.1389728096676737,
 78.66666666666666,
 2.4371772805507748,
 2.340495867768595,
 6.407239819004525,
 4.985915492957746,
 2.0214132762312635,
 2.1734458940905603,
 4.735785953177257,
 2.210772833723653,
 3.416164053075995,
 6.436363636363636,
 46.42622950819672,
 4.233183856502242,
 3.6875,
 3.7911646586345378,
 2.381833473507149,
 8.304985337243401,
 9.254901960784313,
 2.2987012987012987,
 8.79503105590062,
 8.822429906542055,
 2.0808229243203527,
 6.349775784753363,
 4.612377850162867,
 3.6354300385109113,
 3.3714285714285714,
 4.208023774145617,
 6.8076923076923075,
 4.899653979238755,
 4.783783783783784,
 4.841025641025641,
 2.3289473684210527,
 2.1684532924961712,
 3.7019607843137257,
 4.791878172588833,
 4.445839874411303,
 2.6442577030812324,
 2.2440570522979395,
 4.068965517241379,
 2.2949756888168555,
 3.966386554621849,
 7.654054054054054,
 6.251655629139073,
 23.798319327731093,
 2.2387351778656126,
 4.751677852348993,
 2.503978779840849,
 2.1634835752482813,
 2.1454545454545455,
 2.946930280957336,
 2.2511923688394275,
 2.7152444870565677,
 4.122270742358078,
 6.663529411764706,
 2.0521739130434784,
 2.26378896882494,
 2.519572953736655,
 3.160714285714286,
 3.1748878923766815,
 2.8291708291708293,
 12.475770925110131,
 2.0432900432900434,
 2.9347150259067356,
 3.1677852348993287,
 5.2347504621072085,
 4.0806916426512965,
 2.56289592760181,
 2.1229385307346327,
 3.2477064220183487,
 11.849372384937238,
 9.019108280254777,
 5.363636363636363,
 3.2702078521939955,
 2.1717791411042944,
 24.205128205128204,
 7.511936339522547,
 15.910112359550562,
 3.399759903961585,
 7.531914893617022,
 2.1309255079006775,
 2.3959390862944163,
 3.74108322324967,
 2.1953488372093024,
 3.603053435114504,
 2.4842105263157896,
 2.035945363048167,
 25.513513513513512,
 2.8663967611336036,
 26.22222222222222,
 3.441069258809234,
 4.58252427184466,
 2.6417910447761193,
 3.4285714285714284,
 2.191950464396285,
 4.377125193199381,
 2.5467625899280577,
 5.394285714285714,
 2.0315638450502154,
 2.542190305206463,
 3.2218430034129693,
 3.736147757255937,
 3.4368932038834954,
 3.770972037283622,
 2.744186046511628,
 5.962105263157895,
 3.379474940334129,
 7.206106870229008,
 3.31615925058548,
 5.353497164461248,
 3.5488721804511276,
 4.265060240963855,
 27.23076923076923,
 3.2589182968929804,
 2.383838383838384,
 4.882758620689655,
 2.430901287553648,
 2.18013856812933,
 7.3558441558441565,
 2.9195876288659792,
 8.687116564417177,
 2.2710505212510026,
 2.269230769230769,
 6.364044943820225,
 4.418096723868955,
 4.271493212669683,
 3.8954607977991746,
 2.5399103139013453,
 5.111913357400723,
 2.9316770186335406,
 2.8519637462235647,
 2.723076923076923,
 6.824096385542169,
 2.784660766961652,
 2.4540727902946275,
 2.062636562272396,
 3.5311720698254367,
 2.371859296482412,
 6.7913669064748206,
 2.2476190476190476,
 2.6742209631728047,
 3.0031813361611874,
 4.712146422628952,
 2.0838852097130243,
 2.9530761209593326,
 5.887733887733887,
 2.097777777777778,
 9.535353535353536,
 2.5839416058394162,
 3.5984752223634056,
 2.659154929577465,
 2.605335786568537,
 3.6122448979591835,
 4.104347826086957,
 10.7680608365019,
 2.1438304314912946,
 4.0573065902578795,
 8.877742946708464,
 3.750993377483444,
 2.8780487804878048,
 2.5513513513513515,
 19.53103448275862,
 2.185185185185185,
 2.0869565217391304,
 3.3006993006993004,
 2.6125461254612548,
 10.727272727272727,
 3.7609561752988045,
 2.046242774566474,
 2.0113636363636367,
 14.375634517766496,
 17.59006211180124,
 2.2857142857142856,
 2.3678929765886285,
 3.938803894297635,
 2.730954676952748,
 2.1245311327831957,
 2.588665447897623,
 14.984126984126984,
 4.4739336492890995,
 3.0649350649350646,
 3.4038461538461537,
 3.9170124481327804,
 4.619902120717781,
 2.2038910505836578,
 2.193648334624322,
 7.633423180592993,
 2.0243030736240173,
 2.094674556213018,
 3.074918566775244,
 6.601398601398601,
 5.698189134808853,
 2.127723516153268,
 3.4120481927710844,
 2.050687907313541,
 4.2844175491679275,
 4.063127690100431,
 12.699551569506726,
 108.92307692307692,
 12.102564102564102,
 2.061135371179039,
 4.039942938659059,
 3.575757575757576,
 2.4267352185089974,
 3.900826446280992,
 2.4413793103448276,
 3.2968568102444706,
 3.535580524344569,
 3.2439862542955327,
 5.6190476190476195,
 2.5240641711229945,
 2.231678486997636,
 2.150341685649203,
 2.111856823266219,
 8.660550458715596,
 2.0185317177476834,
 2.840521564694082,
 2.115011202389843,
 2.037410071942446,
 3.5622641509433968,
 3.375446960667461,
 5.563850687622789,
 2.2299212598425195,
 5.38403041825095,
 5.323308270676692,
 4.925217391304348,
 3.8688524590163937,
 3.97194950911641,
 3.1362126245847177,
 4.258646616541354,
 2.2894098625707358,
 2.1422087745839637,
 2.8179104477611943,
 2.1835003855050115,
 2.765625,
 4.8576329331046315,
 6.907317073170731,
 2.707456978967495,
 2.015658362989324,
 2.3580349708576187,
 2.8868501529051986,
 5.596837944664031,
 2.4246575342465757,
 2.5559566787003614,
 3.189189189189189,
 3.89010989010989,
 2.15361216730038,
 2.6894586894586894,
 2.064139941690962,
 8.428571428571429,
 2.2264150943396226,
 4.8,
 3.2291904218928162,
 3.1501668520578416,
 4.086580086580087,
 3.0321199143468953,
 6.051282051282051,
 2.3659147869674184,
 2.1902552204176335,
 2.5934065934065935,
 5.8391752577319584,
 3.1258278145695364,
 8.85,
 2.126126126126126,
 9.567567567567568,
 9.6,
 13.550239234449762,
 2.2820306204673653,
 6.3927765237020315,
 4.214285714285714,
 2.219435736677116,
 2.3463131731565867,
 25.28571428571429,
 22.656,
 2.8151093439363817,
 5.435700575815739,
 2.4081632653061225,
 3.192784667418264,
 4.37037037037037,
 2.435081685296647,
 2.7629268292682925,
 2.5330948121645798,
 26.46728971962617,
 2.3327841845140034,
 2.274698795180723,
 6.156521739130435,
 3.658914728682171,
 43.56923076923077,
 3.4876847290640396,
 5.130434782608695,
 2.0056657223796033,
 2.7048710601719197,
 7.801652892561984,
 2.462608695652174,
 9.37748344370861,
 2.8548387096774195,
 2.910585817060637,
 2.2968369829683697,
 2.8235294117647056,
 2.460469157254561,
 4.134306569343066,
 3.544430538172716,
 2.0777696258253853,
 2.327033689400164,
 2.079295154185022,
 2.6029411764705883,
 2.389873417721519,
 4.092485549132948,
 2.694576593720267,
 3.091703056768559,
 4.824531516183986,
 2.342431761786601,
 2.9747899159663866,
 2.3600000000000003,
 2.350207468879668,
 4.2395209580838324,
 3.449451887941535,
 2.0344827586206895,
 2.4668989547038325,
 2.410212765957447,
 2.497354497354497,
 5.488372093023256,
 2.352159468438538,
 2.5792349726775954,
 3.644787644787645,
 2.889795918367347,
 2.315617334423549,
 2.0257510729613735,
 2.1024498886414253,
 2.049204052098408,
 3.2255125284738044,
 2.1470811220621684,
 ...]

In [6]:
def analyze_periods(data, n, th=100):
    N = len(data)
    fft_values = np.fft.fft(data)
    freqs = np.fft.fftfreq(N, d=1)
    
    # Compute magnitudes and filter frequencies within threshold
    magnitudes = np.abs(fft_values[:N//2]) / N
    valid_indices = np.where(np.abs(freqs[:N//2]) <= th)[0]
    
    # Sort frequencies by magnitude in descending order
    sorted_indices = valid_indices[np.argsort(magnitudes[valid_indices])[::-1]]
    
    # Convert frequencies to periods (T = 1/f) while avoiding division by zero
    periods = [1 / freqs[i] if freqs[i] != 0 else np.inf for i in sorted_indices]
    
    return periods

In [7]:
k

,kingdom,Avg_Temperature,Radiation,Rain_Amount,Wind_Speed,Wind_Direction
Date,,,,,,
2019-04-01,Winterfell,23.0,21.87,11.31,10.5,167
2019-04-02,Winterfell,23.0,24.37,10.40,9.9,227
2019-04-03,Winterfell,23.3,20.23,22.23,4.8,354
2019-04-04,Winterfell,24.3,24.84,0.65,5.7,308
2019-04-05,Winterfell,24.3,24.44,1.17,8.0,182
...,...,...,...,...,...,...
2026-12-27,Winterfell,22.4,22.18,0.26,8.7,142
2026-12-28,Winterfell,21.9,18.89,3.51,10.5,81
2026-12-29,Winterfell,21.8,23.23,0.00,12.6,76
2026-12-30,Winterfell,20.3,23.35,0.00,10.7,66
2026-12-31,Winterfell,20.1,21.31,0.00,9.4,53

In [4]:
preds = list()

end_date = to_date(9, 5, 31)


for k in kingdoms:
    n_preds = (end_date-k.index[-1]).days
    name = k['kingdom'].unique()[0]
    print(name)
    k_fet = k[target].to_numpy().T
    k_pred = predict_many(k[target].to_numpy().T, n_preds).T
    dw = create_next_date_window_n(k.index[-1], n_preds)
    pred_df = create_dataframe(dw, k_pred, target, {'kingdom': name})
    preds.append(pred_df)
df_pred = pd.concat(preds, axis=0)

Arcadia
Atlantis
Avalon
Camelot
Dorne
Eden
El Dorado
Elysium
Emerald City
Helios
Krypton
Metropolis
Midgar
Midgard
Mordor
Neo-City
Neo-Tokyo
Nirvana
Olympus
Pandora
Rapture
Rivendell
Serenity
Shangri-La
Solara
Solstice
Sunspear
Utopia
Valyria
Winterfell

In [5]:
def get_pred(year, month, day, kingdom):
    return df_pred[(df_pred.index == to_date(year, month, day)) & (df_pred['kingdom']==kingdom)]

In [31]:
train_df = pd.read_csv('/kaggle/input/data-crunch-round-1/train.csv')
test_df = pd.read_csv('/kaggle/input/data-crunch-round-1/test.csv')
id_cols = ['ID', 'Year', 'Month', 'Day', 'kingdom']

id_df = pd.concat([train_df[id_cols], test_df[id_cols]], axis=0)
id_df.set_index('ID', inplace=True)

def pred_from_id(id):
    r = id_df[id_df.index==id]
    year, month, day, kingdom = r.iloc[0].to_numpy()
    return get_pred(year, month, day, kingdom)[target].to_numpy()[0]

In [33]:
def pred_from_ids(ids):
    final_pred = list(map(pred_from_id, ids))
    final_pred_df = create_dataframe(ids, final_pred, target)
    final_pred_df = final_pred_df.reset_index().rename(columns={'index': 'ID'})
    final_pred_df['Avg_Temperature'] = final_pred_df['Avg_Temperature'].apply(lambda x: x - 273.15 if x > 200 else x)
    return final_pred_df

In [45]:
ids = pd.read_csv("/kaggle/input/data-crunch-round-1/train.csv")['ID'].to_numpy()
ids[:100]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [35]:
pred_df

,ID,Avg_Temperature,Radiation,Rain_Amount,Wind_Speed,Wind_Direction
0,84961,25.787852,22.020727,16.025933,11.832419,247.436357
1,84962,27.405727,23.293370,8.069073,14.470094,213.731812
2,84963,26.915160,23.293370,8.069073,14.470094,213.731812
3,84964,23.832505,21.362747,31.359934,9.883312,153.919217
4,84965,28.027483,22.103871,2.902246,19.867404,227.368844
...,...,...,...,...,...,...
4525,89486,28.676827,23.623594,2.216718,23.936603,237.986883
4526,89487,28.376126,23.806337,2.814234,31.140017,224.492631
4527,89488,26.750045,19.997153,7.400376,16.412326,232.541027
4528,89489,28.571267,22.786278,3.103946,16.275112,184.610298
4529,89490,24.688157,22.180075,7.191846,12.184748,248.815316

In [40]:
ids = train_df['ID'].to_numpy()
pred_df = pred_from_ids(ids)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [5]:
df = pd.read_csv("/kaggle/input/data-crunch-round-1/train.csv")
df['Date'] = df.apply(lambda row: datetime(year=2018+row['Year'], 
                                                     month=row['Month'], 
                                                     day=row['Day']), axis=1)
df

,ID,Year,Month,Day,kingdom,latitude,longitude,Avg_Temperature,Avg_Feels_Like_Temperature,Temperature_Range,Feels_Like_Temperature_Range,Radiation,Rain_Amount,Rain_Duration,Wind_Speed,Wind_Direction,Evapotranspiration,Date
0,1,1,4,1,Arcadia,24.280002,-37.229980,25.50,30.50,8.5,10.3,22.52,58.89,16,8.6,283,1.648659,2019-04-01
1,2,1,4,1,Atlantis,22.979999,-37.329990,299.65,305.15,5.9,8.2,22.73,11.83,12,15.8,161,1.583094,2019-04-01
2,3,1,4,1,Avalon,22.880000,-37.130006,26.30,31.50,5.2,6.4,22.73,11.83,12,15.8,161,1.593309,2019-04-01
3,4,1,4,1,Camelot,24.180003,-36.929994,24.00,28.40,8.2,10.7,22.67,75.27,16,6.4,346,1.638997,2019-04-01
4,5,1,4,1,Dorne,25.780002,-37.530000,28.00,32.80,5.7,10.2,22.35,4.81,8,16.7,185,1.719189,2019-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84955,84956,8,12,31,Solstice,25.479998,-36.329990,25.60,28.60,3.4,3.5,19.41,0.13,1,14.8,90,1.562346,2026-12-31
84956,84957,8,12,31,Sunspear,26.580005,-37.530000,25.80,28.90,2.8,3.7,20.98,0.26,2,16.3,91,1.607436,2026-12-31
84957,84958,8,12,31,Utopia,23.979999,-37.630006,298.75,301.65,7.6,9.2,22.67,0.00,0,12.6,71,1.710188,2026-12-31
84958,84959,8,12,31,Valyria,24.280002,-35.729980,25.60,28.10,4.0,3.8,19.72,0.00,0,16.3,54,1.613430,2026-12-31
84959,84960,8,12,31,Winterfell,23.979999,-36.429994,20.10,21.50,8.4,11.1,21.31,0.00,0,9.4,53,1.539015,2026-12-31